services:
  - type: web
    name: notr-afrik
    runtime: node
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npm run build && cd ../client && npm install && npm run build
    startCommand: cd server && npx prisma db push && npx prisma db seed && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://notr-afrik.onrender.com
      - key: DATABASE_URL
        sync: false
